# Site settings
title: The Serial Mentor
description: > # this means to ignore newlines until "baseurl:"
  Science, Writing, Fitness, Nutrition, Professional Development
baseurl: "" # the subpath of the site, e.g. /blog/
url: "http://serialmentor.com" # the base hostname & protocol
permalink: /blog/:year/:i_month/:i_day/:title
excerpt_separator: <!--more-->
gems: [jekyll-paginate]
paginate: 12
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
highlighter: rouge
sass:
    style: :compressed
    
# kramdown settings
kramdown:
  input: GFM
